### PR TITLE
Added examples and tests for Meronyms and Homonymys

### PR DESCRIPTION
**Pull request by MayankGoel28**
I based these on my understanding of meronyms/holonyms (using Wikipedia) as a reference, as well as Saeed's Semantics as a primary reference.

### CODE REVIEW

**Comment by goodmami** [comment]
Thanks! The `index.html` file is generated from the data (see instructions [here](https://github.com/globalwordnet/gwadoc#building-the-documentation)). Can you please put the content in the appropriate place in the [doc_en.py](../blob/master/gwadoc/doc_en.py) file?

**Comment by MayankGoel28** [comment]
My bad, I thought the python script was for the dictionary and not for the documentation itself. Doing the needful.

**Comment by goodmami** [comment]
No worries. There's no need to close the PR. You could just update your fork with a new commit.

**Comment by MayankGoel28** [comment]
@goodmami Done. I created a new PR for that.

**Comment by goodmami** [comment]
@MayankGoel28 ok thanks, but in the future just keep the same PR instead of creating a new one. That way the conversation stays together.

**Comment by MayankGoel28** [comment]
Okay, I will keep that in mind.

**Pull request closed without merging**
