### PR TITLE
Create Overview section

### PR DESCRIPTION
**Pull request by yoyo-go**
Add a brief intro of wordnet.

### CODE REVIEW

**Comment by yoyo-go** [comment]
Please let me know if you think more topic needs to be added to this section.

**Comment by fcbond** [comment]
This helps a lot in giving some idea of what is going on.

I think it is important to format a bit more for readability.  Words being mentioned should be italicized and ideally linked to wordnet: "such as _shut_ and _close_".

We should also link to at least Princeton Wordnet and the Open Multilingual Wordnet.

**Comment by yoyo-go** [comment]
> This helps a lot in giving some idea of what is going on.
> 
> I think it is important to format a bit more for readability. Words being mentioned should be italicized and ideally linked to wordnet: "such as _shut_ and _close_".
> 
> We should also link to at least Princeton Wordnet and the Open Multilingual Wordnet.

The links have been added, please let me know if you think any info is still missing in this section.

**Comment by fcbond** [comment]
Looks good to me!  Closes #54.

**Pull request merged**
